### ISSUE TITLE
checkbox set angle is invalidate

### ISSUE THREAD

**Issue by lanyan520** [aleSheng/sd-webui-dragGAN-extension#1]
这个插件是还没开发好么？angle 设置了，发现生成没效果，drangan.py  process_images(p)？看不懂，还是我用法错误了

**Comment by Cra1gTucker** [comment]
1. 是的，这个插件目前只是模板而已。
2. 如果你看一下DragGAN的文档，你会发现它是需要对GAN的latent空间进行操作的，而SD并不是一个GAN。而文档中也提到了，如果想对非GAN生成的图片进行操作，需要用类似PTI的方法进行反转操作获得图片在latent空间的近似表示（这需要一定时间的开发和代码量），所以想在SD中用DragGAN本身就是一种不是很有意义的操作，没必要再关注了。
---
1. Yes, this extension is currently only a stub with little development.
2. If you read through the documentation of DragGAN, you'll find that it achieves its objective by manipulating on latent space of the GAN (SD is not a GAN). Also mentioned in the documentation, if you want to edit an image not created by a GAN, you must first acquire its representation in a GAN's latent space by using inversion methods like PTI (requires certain amount of development effort to implement). Thus, it is not really viable to use DragGAN along with SD. **I reckon that any development in this direction will not yield meaningful results.**
